### ISSUE TITLE
Error on Use a Emote

### ISSUE THREAD

**Issue by NachtschattenAlexa** [Kiroho/EmoteTome#5]
I get an Error Message and nothing happens:

"Not possible while a key is pressed"

Best regards

Nachtschatten

**Comment by Kiroho** [comment]
The module has some "security checks" to prevent problems. 
Emotes can't be played while in combat, moving, on mount or while any key on your keyboard is pressed (like holding E for turning around). 

If this message occoures while not pressing a key, please let me know.

**Comment by NachtschattenAlexa** [comment]
Hello, i do nothing. No Key, no moving, no combat. Am 06.09.2023 um 14:07 schrieb Kiroho ***@***.***>:﻿
The module has some "security checks" to prevent problems.
Emotes can't be played while in combat, moving, on mount or while any key on your keyboard is pressed (like holding E for turning around).
If this message occoures while not pressing a key, please let me know.

**Comment by Kiroho** [comment]
That's strange. 
Do you have any special hard- or software by any chance? 
Like a keyboard with macros, special software for keyboard/mouse or such?

**Comment by NachtschattenAlexa** [comment]
Hello, it works now, after the Update Am 06.09.2023 um 15:39 schrieb Alexander Decius ***@***.***>:﻿Hello, i do nothing. No Key, no moving, no combat. Am 06.09.2023 um 14:07 schrieb Kiroho ***@***.***>:﻿
The module has some "security checks" to prevent problems.
Emotes can't be played while in combat, moving, on mount or while any key on your keyboard is pressed (like holding E for turning around).
If this message occoures while not pressing a key, please let me know.

**Comment by Kiroho** [comment]
Good to hear. I still will keep an eye on this. :)
