### ISSUE TITLE
Add new unleash emote

### ISSUE THREAD

**Issue by lordchilli** [Kiroho/EmoteTome#8]
Hi, 
please add the unlockable unleash emote:
https://wiki.guildwars2.com/wiki/%22/Unleash%22_Emote_Tome

icon: https://wiki.guildwars2.com/images/thumb/3/3a/%22Unleash%22_Emote_Tome.png/40px-%22Unleash%22_Emote_Tome.png
chat command: /unleash

Many thanks :-)

**Comment by Kiroho** [comment]
Hi, 
I'm currently writing my bachelor thesis, so I don't have much free time. 
I will add the new emote as soon as I can, but it's not possible within the next 2-3 weeks. 

I'm sorry for the inconvenience and ask you for your understanding an patience. :-)

**Comment by lordchilli** [comment]
ok:-)

Good luck with your bachelor thesis :-)
